esphome:
  name: human-detector
  includes:
    - mmWaveRadar.h

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "secret"

ota:
  password: "secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Home-Wifi Fallback Hotspot"
    password: "T4fomkuKVCJ6"


uart:
  id: uart1
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     bytes: 1


custom_component:
  - lambda: |-
      return {new HumanPresenceRadar(id(uart1))};
    components:
      - id: mmWave


binary_sensor:
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<HumanPresenceRadar *>(mmWave);
      return {uart_component->target_present};
    binary_sensors:
      name: "Human presense"

sensor:
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<HumanPresenceRadar *>(mmWave);
      return {uart_component->body_movement};
    sensors:
      name: "Body movement description"
      unit_of_measurement: "%"
  
text_sensor:
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<HumanPresenceRadar *>(mmWave);
      return {uart_component->heart_beat_sensor};
    text_sensors:
      name: "Heart Beat information"
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<HumanPresenceRadar *>(mmWave);
      return {uart_component->approching_away_sensor};
    text_sensors:
      name: "Approaching away state"
